---
title: "R_project_MBA"
author: "Narang,Mandeep"
date: "11/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

Retail_data<- read.csv("Online Retail.csv")##Reading the Raw dataset and naming as Retail_data

```



```{r}
## Installing Required packages
##we need to perform some data manipulation so we have attached the concern libraries
library(dplyr)
library(arules)
library(arulesViz)
library(tidyverse)
library(stringr)
library(lubridate)
library(ggplot2)
```


```{r}
class(Retail_data) ## Viewing the Raw data file
##taking first look on the data by checking class , dimension, structure, summary and some of the records from top and bottom.
dim(Retail_data)
names(Retail_data)
glimpse(Retail_data)
summary(Retail_data)
head(Retail_data)
tail(Retail_data)

```


```{r}
## Manipulating the Date column, making the dates in Date format and looking for the changes those have been made
## creating newcolumns for Date Month and year and then consolidating all in single data frame
## looking at the sumary of the new data

Retail_data$InvoiceDate <- mdy_hm(Retail_data$InvoiceDate)
Time<- hour(Retail_data$InvoiceDate)
new_date<- as.Date(format(Retail_data$InvoiceDate,"%Y-%m-%d"))
new_month<- month(Retail_data$InvoiceDate)
new_year<- year(Retail_data$InvoiceDate)
Retail_data<-data.frame(Retail_data,new_date,new_month,new_year,Time)  

summary(Retail_data)
head(Retail_data)

```




```{r}
## Creating final data set for the model
## Removing the missing entries in the item field
flag1<-Retail_data$Description !=""
Retail_data_wip2<- Retail_data[flag1,c(1,3)]
```


```{r}
##converting Data frame to transactions

write.csv(Retail_data_wip2, file = "Retail_trans.csv")
trans = read.transactions("Retail_trans.csv", format = "single", sep = ",", cols = c("InvoiceNo", "Description"))
inspect(trans[1:5])
```


```{r}
## running the model and sorting the results by confidence
## inspecting the rules

rules = apriori(trans,parameter = list(supp = 0.001,conf=0.8))
rules<- sort(rules,by= "confidence",decreasing = "T")
inspect(rules[1:10])
```



